[project]
name = "bajaj-insurance-rag-based-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=6.0.1",
    "numpy>=2.2.6",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
